basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print("basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}")
print(basket)
print("'orange' in basket",'orange' in basket)
print("'crabgrass' in basket",'crabgrass' in basket)
a = set('abracadabra')
print("a = set('abracadabra')")
print(a)
b=set('alacazam')
print("b=set('alacazam')")
print(b)
print("a-b",a-b)
print("a|b",a|b)
print("a&b",a&b)
print("a^b",a^b)

print("********1.添加元素*******")
thisset = set(("Google", "Runoob", "Taobao"))
print("thisset = set(('Google', 'Runoob', 'Taobao'))")
print(thisset)
print("thisset.add('Facebook')")
thisset.add("Facebook")
print(thisset)
thisset.update({1, 3})
print("thisset.update({1, 3})")
print(thisset)
thisset.update([1,4],[5,6])
print("thisset.update([1,4],[5,6])")
print(thisset)

print("********2.移除元素*******")
#thisset.remove('Taobao')
print("thisset.remove('Taobao')")
print(thisset)
print("remove()移除不存在的元素会报错")
print("this.discatd('Facebook')")
thisset.discard('Facebook')
#thisset.pop()
print("thisset.pop()随机删除")
print(thisset)

print("********3.计算集合元素个数*******")
print("len(thisset): ",len(thisset))

print("********4.判断元素是否存在*******")
print("'Taobao' in thisset: ",'Taobao' in thisset)
print("'Taobao1' not in thisset: ",'Taobao1' not in thisset)

print("********5.清空集合*******")
thisset.clear()
print("thisset.clear()")
print("len(thisset): ",len(thisset))

print("********6.print语句中的end的用法*******")
for i in range(1,10):
    print(i,end=" ")

